AllCops:
  TargetRubyVersion: 3.0.0
  NewCops: enable

require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

Performance:
  Enabled: true

Security:
  Enabled: true

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  CountComments: false
  Exclude:
    - 'spec/**/*.rb'
    - '**/*.gemspec'

Metrics/ClassLength:
  CountComments: false

Metrics/MethodLength:
  CountComments: false

Metrics/ModuleLength:
  CountComments: false
