AllCops:
  TargetRubyVersion: 3.0.0
  NewCops: enable

require:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-performance

Performance:
  Enabled: true

Security:
  Enabled: true

Layout/LineLength:
  Max: 120
